- name: Rosdep Initialization
  become: true
  ansible.builtin.command:
    cmd: rosdep init
    creates: "{{ rosdep_init_path }}"
  when: init_rosdep

- name: Rosdep Update
  ansible.builtin.command:
    cmd: rosdep update
  changed_when: true

- name: Rosdep Install
  ansible.builtin.shell:
    cmd: "source /opt/ros/{{ ros_distro }}/setup.bash && rosdep install --from-paths . --ignore-src --rosdistro {{ ros_distro }} -r -y"
  args:
    executable: /bin/bash
    chdir: "{{ ros_source_dir }}"
  changed_when: true
