---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Install CUDA Toolkit Packages
      ansible.builtin.include_role:
        name: bounverif.ros.cuda_toolkit_install
      vars:
        cuda_toolkit_install_packages:
          - cuda-nvcc-12-4
