- name: Install Repositories - From File
  ansible.builtin.include_tasks: from_file.yml
  when: repositories_files is defined

- name: Install Repositories - From Variable
  ansible.builtin.include_tasks: from_variable.yml
  when: repositories_files is undefined
