---
- name: Build Autoware and dependencies
  hosts: localhost
  connection: local
  vars:
    ros_distro: humble
    ros_distro_type: desktop
    autoware_version: main
    autoware_ws: /tmp/autoware
    autoware_src: "{{ autoware_ws }}/src"
    autoware_install_dir: "/opt/autoware/{{ ros_distro }}"
    ros_repos_path: "./"
    repositories: "{{ lookup('file', ros_repos_path + 'repo.repos') | ansible.builtin.from_yaml }}"

  roles:
    - role: bounverif.ros.get_repos

