- name: Setup ROS 2 keys
  ansible.builtin.apt_key:
    url: "{{ ros2_gpg_key_url }}"
    state: present
  become: true

- name: Add the Repository to Sources List
  ansible.builtin.apt_repository:
    repo: "deb {{ ros_repository_url }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: true
  become: true

- name: Install ROS 2 Packages
  ansible.builtin.apt:
    name: "{{ ros2_install_packages }}"
    state: present
    update_cache: true
  become: true
