- name: Install cuda-keyring for Debian family
  become: true
  ansible.builtin.apt:
    deb: '{{ cuda_toolkit_install_debian_family_keyring_file_url }}'

- name: Install packages via apt
  become: true
  ansible.builtin.apt:
    name: "{{ cuda_toolkit_install_packages }}"
    state: present
    update_cache: true