- name: Install cuda-keyring for Debian
  become: true
  ansible.builtin.apt:
    deb: '{{ cuda_keyring_url_base }}/{{ cuda_keyring_file_name }}'
  when: hostvars[inventory_hostname].ansible_os_family == "Debian"

- name: Install cuda-keyring for OpenSuse
  become: true
  zypper_repository: # noqa: fqcn[action]
    repo: "{{ cuda_keyring_url_base }}/"
    name: "{{ cuda_keyring_file_name }}"
    state: present
    runrefresh: true
    auto_import_keys: true
  when: hostvars[inventory_hostname].ansible_os_family == "Suse"

- name: Update apt-get
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 0
  when: hostvars[inventory_hostname].ansible_os_family == "Debian"

- name: Install cuda-toolkits for Debian
  become: true
  ansible.builtin.apt:
    force_apt_get: true
    name: "{{ item }}"
  loop: "{{ cuda_toolkit_install_packages }}"
  when: hostvars[inventory_hostname].ansible_os_family == "Debian"

- name: Install cuda-toolkits for OpenSuse
  become: true
  zypper: # noqa: fqcn[action]
    force: true
    name: "{{ item }}"
  loop: "{{ cuda_toolkit_install_packages }}"
  when: hostvars[inventory_hostname].ansible_os_family == "Suse"
