- name: Get cuda-keyring File
  become: true
  ansible.builtin.get_url:
    url: "{{ cuda_keyring_url | replace('linux_version', linux_version) | replace('system_architecture', system_architecture) }}"
    dest: "{{ cuda_keyring_dest }}"
    mode: '0440'

- name: Install cuda-keyring
  become: true
  ansible.builtin.apt:
    deb: "{{ cuda_keyring_dest }}"

- name: Remove cuda-keyring File
  ansible.builtin.file:
    path: "{{ cuda_keyring_dest }}"
    state: absent

- name: Update apt-get
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 0

- name: Install cuda-toolkits
  become: true
  ansible.builtin.apt:
    force_apt_get: true
    name: "{{ item }}"
  loop: "{{ toolkits }}"
