- name: Install cuda-keyring
  become: true
  ansible.builtin.apt:
    deb: "{{ cuda_keyring_url }}"

- name: Update apt-get
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 0

- name: Install cuda-toolkits
  become: true
  ansible.builtin.apt:
    force_apt_get: true
    name: "{{ item }}"
  loop: "{{ cuda_toolkit_install_packages }}"
