# system architecture
- name: Set cuda_toolkit_install_arch for x86_64 as fact
  ansible.builtin.set_fact:
    cuda_toolkit_install_arch: "x86_64"
  when: hostvars[inventory_hostname].ansible_machine == 'x86_64'

- name: Set cuda_toolkit_install_arch for arm as fact
  ansible.builtin.set_fact:
    cuda_toolkit_install_arch: "sbsa"
  when: hostvars[inventory_hostname].ansible_machine == 'aarch64'

# linux_version
- name: Set cuda_toolkit_install_distribution as fact
  ansible.builtin.set_fact:
    cuda_toolkit_install_distribution: >-
      {{ hostvars[inventory_hostname].ansible_distribution | lower ~
      hostvars[inventory_hostname].ansible_distribution_version | replace('.','') }}
