# system architecture
- name: Set cuda_toolkit_install_arch for x86_64 as fact
  ansible.builtin.set_fact:
    cuda_toolkit_install_arch: "x86_64"
  when: hostvars[inventory_hostname].ansible_machine == 'x86_64'

- name: Set cuda_toolkit_install_arch for arm as fact
  ansible.builtin.set_fact:
    cuda_toolkit_install_arch: "sbsa"
  when: hostvars[inventory_hostname].ansible_machine == 'aarch64'

# linux_version
- name: Set cuda_toolkit_install_distribution for Debian as fact
  ansible.builtin.set_fact:
    cuda_toolkit_install_distribution: >-
      {{ hostvars[inventory_hostname].ansible_distribution | lower ~
      hostvars[inventory_hostname].ansible_distribution_version | replace('.','') }}
  when: hostvars[inventory_hostname].ansible_os_family == "Debian"

- name: Set cuda_toolkit_install_distribution for OpenSuse as fact
  ansible.builtin.set_fact:
    cuda_toolkit_install_distribution: >-
      {{ hostvars[inventory_hostname].ansible_distribution | lower | regex_search('([^\s]+)')  ~
      hostvars[inventory_hostname].ansible_distribution_version | regex_search('^[^.]*') }}
  when: hostvars[inventory_hostname].ansible_os_family == "Suse"

# keyring file name
- name: Set cuda-keyring-file for Debian
  ansible.builtin.set_fact:
    cuda_keyring_file_name: cuda-keyring_1.1-1_all.deb
  when: hostvars[inventory_hostname].ansible_os_family == "Debian"

- name: Set cuda-keyring-file for OpenSuse Leap
  ansible.builtin.set_fact:
    cuda_keyring_file_name: cuda-{{ cuda_toolkit_install_distribution }}.repo
  when: hostvars[inventory_hostname].ansible_os_family == "Suse"
