# system architecture
- name: Set architecture for Amd64
  ansible.builtin.set_fact:
    cuda_toolkit_install_arch: "x86_64"
  when: ansible_machine == 'x86_64' and cuda_toolkit_install_arch is not defined

- name: Set architecture for Arm64
  ansible.builtin.set_fact:
    cuda_toolkit_install_arch: "sbsa"
  when: ansible_machine == 'aarch64' and cuda_toolkit_install_arch is not defined
